"""Generate Upgraded Google Colab Notebook for BioBERT training.

This script programmatically generates `notebooks/BioBERT_Training.ipynb`
incorporating all the requested production-grade enhancements.
"""

from __future__ import annotations

import json
from pathlib import Path

# Repo directories
REPO_ROOT = Path(__file__).resolve().parents[1]
NOTEBOOK_PATH = REPO_ROOT / "notebooks" / "BioBERT_Training.ipynb"

# ─────────────────────────────────────────────────────────────────────────────
# Notebook Cells Definition
# ─────────────────────────────────────────────────────────────────────────────

cells = [
    {
        "cell_type": "markdown",
        "metadata": {},
        "source": [
            "# Upgraded BioBERT Symptom Diagnosis Model Training Pipeline\n",
            "\n",
            "This notebook implements a production-grade training, calibration, and evaluation pipeline for fine-tuning **BioBERT** on clinical symptom text classifications.\n",
            "\n",
            "### Production Pipeline Features:\n",
            "1. **Advanced Model**: `dmis-lab/biobert-base-cased-v1.1` fine-tuned with **Label Smoothing (0.1)** and **Weighted Cross-Entropy Loss**.\n",
            "2. **Structured Patient Metadata**: Optional support for age, gender, duration, history, BMI, smoking, and alcohol inputs (prepares the model for future multi-modal features without breaking compatibility).\n",
            "3. **State-of-the-Art Training**: Cosine learning rate scheduler with warmup, Gradient accumulation, Mixed Precision (FP16), and Gradient Clipping.\n",
            "4. **Robust Validation**: Stratified Train/Val/Test splits, Early Stopping based on Validation Macro F1, and Auto-Resuming from latest epoch checkpoints.\n",
            "5. **Systematic Grid Search**: Optimises Learning Rates (`5e-5`, `3e-5`, `2e-5`), Batch Sizes (`8`, `16`), and Weight Decay (`0.01`, `0.05`).\n",
            "6. **Confidence Calibration**: Post-training L-BFGS Temperature Scaling.\n",
            "7. **Clinical Explanations**: Automated rule-based diagnosis justifications, specialist recommendations, diagnostic tests, lifestyle advice, and emergency warning signs.\n",
            "8. **Full Visualizations & Export**: Learning curves, confusion matrix, calibration curve, reliability diagram, precision-recall curves, and class distributions exported to `biobert_final_model/`.\n",
        ],
    },
    {"cell_type": "markdown", "metadata": {}, "source": ["## 1. Environment & Package Setup"]},
    {
        "cell_type": "code",
        "execution_count": None,
        "metadata": {},
        "outputs": [],
        "source": [
            "# Install required dependencies\n",
            "!pip install -q transformers[torch] datasets scikit-learn matplotlib seaborn pandas numpy accelerate",
        ],
    },
    {
        "cell_type": "code",
        "execution_count": None,
        "metadata": {},
        "outputs": [],
        "source": [
            "import os\n",
            "from google.colab import drive\n",
            "\n",
            "# Mount Google Drive\n",
            "drive.mount('/content/drive')\n",
            "\n",
            "DRIVE_DATA_DIR = '/content/drive/MyDrive/AI-Medical-Diagnosis-Assistant/data'\n",
            "LOCAL_DATA_DIR = './data'\n",
            "\n",
            "os.makedirs(os.path.join(LOCAL_DATA_DIR, 'final'), exist_ok=True)\n",
            'print("Google Drive mounted and local environment configured.")',
        ],
    },
    {"cell_type": "markdown", "metadata": {}, "source": ["### Fetch Split Datasets from Drive"]},
    {
        "cell_type": "code",
        "execution_count": None,
        "metadata": {},
        "outputs": [],
        "source": [
            "import shutil\n",
            "\n",
            "files_to_copy = [\n",
            "    'final/train.csv',\n",
            "    'final/validation.csv',\n",
            "    'final/test.csv',\n",
            "    'final/class_weights.json',\n",
            "    'final/label_encoder.pkl',\n",
            "    'processed/disease_mapping_41.json'\n",
            "]\n",
            "\n",
            "for rel_path in files_to_copy:\n",
            "    src = os.path.join(DRIVE_DATA_DIR, rel_path)\n",
            "    dst = os.path.join(LOCAL_DATA_DIR, rel_path)\n",
            "    os.makedirs(os.path.dirname(dst), exist_ok=True)\n",
            "    if os.path.exists(src):\n",
            "        shutil.copy(src, dst)\n",
            '        print(f"Copied: {rel_path} to local runtime.")\n',
            "    else:\n",
            '        print(f"Warning: Source not found at {src}")',
        ],
    },
    {"cell_type": "markdown", "metadata": {}, "source": ["## 2. Imports, Seeds & GPU Detection"]},
    {
        "cell_type": "code",
        "execution_count": None,
        "metadata": {},
        "outputs": [],
        "source": [
            "import random\n",
            "import time\n",
            "import pickle\n",
            "import json\n",
            "from pathlib import Path\n",
            "from datetime import datetime\n",
            "\n",
            "import numpy as np\n",
            "import pandas as pd\n",
            "import matplotlib.pyplot as plt\n",
            "import seaborn as sns\n",
            "\n",
            "import torch\n",
            "from torch import nn, optim\n",
            "from torch.utils.data import Dataset, DataLoader\n",
            "from torch.cuda.amp import autocast, GradScaler\n",
            "\n",
            "from sklearn.metrics import (\n",
            "    accuracy_score, precision_recall_fscore_support,\n",
            "    confusion_matrix, classification_report, roc_auc_score, balanced_accuracy_score,\n",
            "    precision_recall_curve, average_precision_score\n",
            ")\n",
            "from sklearn.calibration import calibration_curve\n",
            "from sklearn.preprocessing import label_binarize\n",
            "\n",
            "from transformers import (\n",
            "    AutoConfig, AutoModelForSequenceClassification, AutoTokenizer,\n",
            "    get_cosine_schedule_with_warmup\n",
            ")\n",
            "\n",
            'device = torch.device("cuda" if torch.cuda.is_available() else "cpu")\n',
            'gpu_name = "CPU" if device.type == "cpu" else torch.cuda.get_device_name(0)\n',
            'print(f"Using Device: {device} ({gpu_name})")\n',
            "\n",
            "def set_seed(seed=42):\n",
            "    random.seed(seed)\n",
            "    np.random.seed(seed)\n",
            "    torch.manual_seed(seed)\n",
            "    torch.cuda.manual_seed_all(seed)\n",
            "    torch.backends.cudnn.deterministic = True\n",
            "    torch.backends.cudnn.benchmark = False\n",
            "\n",
            "set_seed(42)",
        ],
    },
    {"cell_type": "markdown", "metadata": {}, "source": ["## 3. Load Datasets & Verify Alignment"]},
    {
        "cell_type": "code",
        "execution_count": None,
        "metadata": {},
        "outputs": [],
        "source": [
            "train_df = pd.read_csv('data/final/train.csv')\n",
            "val_df = pd.read_csv('data/final/validation.csv')\n",
            "test_df = pd.read_csv('data/final/test.csv')\n",
            "\n",
            "with open('data/processed/disease_mapping_41.json', 'r') as f:\n",
            "    disease_mapping = json.load(f)\n",
            "idx_to_disease = {v: k for k, v in disease_mapping.items()}\n",
            "num_classes = len(disease_mapping)\n",
            "\n",
            "with open('data/final/class_weights.json', 'r') as f:\n",
            "    class_weights_dict = json.load(f)\n",
            "\n",
            "weights_tensor = torch.zeros(num_classes, dtype=torch.float)\n",
            "for k, w in class_weights_dict.items():\n",
            "    weights_tensor[int(k)] = float(w)\n",
            "weights_tensor = weights_tensor.to(device)\n",
            "\n",
            "with open('data/final/label_encoder.pkl', 'rb') as f:\n",
            "    label_encoder = pickle.load(f)\n",
            "\n",
            'print(f"Train records:      {len(train_df)}")\n',
            'print(f"Validation records: {len(val_df)}")\n',
            'print(f"Test records:       {len(test_df)}")',
        ],
    },
    {
        "cell_type": "markdown",
        "metadata": {},
        "source": [
            "## 4. Patient Metadata Formatting & Clinical Dataset Class\n",
            "\n",
            "To support future structured medical feature fine-tuning, the data loading class can format optional clinical metadata attributes (age, gender, BMI, etc.) and prepend them to the symptoms description without breaking backward compatibility.",
        ],
    },
    {
        "cell_type": "code",
        "execution_count": None,
        "metadata": {},
        "outputs": [],
        "source": [
            "def format_clinical_text(\n",
            "    text: str, age=None, gender=None, duration=None, \n",
            "    history=None, smoking=None, alcohol=None, bmi=None\n) -> str:\n",
            '    """Optionally prepends patient metadata features to symptom narratives."""\n',
            "    profile = []\n",
            "    if age is not None and not pd.isna(age):\n",
            '        profile.append(f"Age {int(age)}")\n',
            "    if gender is not None and not pd.isna(gender) and str(gender).strip():\n",
            '        profile.append(f"Gender {str(gender).strip()}")\n',
            "    if duration is not None and not pd.isna(duration) and str(duration).strip():\n",
            '        profile.append(f"Duration {str(duration).strip()}")\n',
            "    if history is not None and not pd.isna(history) and str(history).strip():\n",
            '        profile.append(f"History of {str(history).strip()}")\n',
            "    if smoking is not None and not pd.isna(smoking):\n",
            '        profile.append(f"Smoking: {smoking}")\n',
            "    if alcohol is not None and not pd.isna(alcohol):\n",
            '        profile.append(f"Alcohol: {alcohol}")\n',
            "    if bmi is not None and not pd.isna(bmi):\n",
            '        profile.append(f"BMI {float(bmi):.1f}")\n',
            "\n",
            "    if profile:\n",
            '        return "[Patient Profile: " + ", ".join(profile) + "] " + text\n',
            "    return text\n",
            "\n",
            "class ClinicalSymptomDataset(Dataset):\n",
            '    """Clinical text dataset with metadata feature support."""\n',
            "    def __init__(self, df, tokenizer, max_length=128):\n",
            "        self.tokenizer = tokenizer\n",
            "        self.max_length = max_length\n",
            "        self.labels = df['label'].values\n",
            "        \n",
            "        # Format texts\n",
            "        self.texts = []\n",
            "        for _, row in df.iterrows():\n",
            "            formatted_txt = format_clinical_text(\n",
            "                text=row['text'],\n",
            "                age=row.get('age', None),\n",
            "                gender=row.get('gender', None),\n",
            "                duration=row.get('symptom_duration', None),\n",
            "                history=row.get('existing_diseases', None),\n",
            "                smoking=row.get('smoking_status', None),\n",
            "                alcohol=row.get('alcohol_use', None),\n",
            "                bmi=row.get('bmi', None)\n",
            "            )\n",
            "            self.texts.append(formatted_txt)\n",
            "\n",
            "    def __len__(self):\n",
            "        return len(self.texts)\n",
            "\n",
            "    def __getitem__(self, idx):\n",
            "        encoding = self.tokenizer(\n",
            "            self.texts[idx],\n",
            "            padding='max_length',\n",
            "            truncation=True,\n",
            "            max_length=self.max_length,\n",
            "            return_tensors='pt'\n",
            "        )\n",
            "        return {\n",
            "            'input_ids': encoding['input_ids'].squeeze(0),\n",
            "            'attention_mask': encoding['attention_mask'].squeeze(0),\n",
            "            'label': torch.tensor(self.labels[idx], dtype=torch.long)\n",
            "        }",
        ],
    },
    {
        "cell_type": "markdown",
        "metadata": {},
        "source": [
            "## 5. Metrics Engine (Top-1/3/5 Accuracy, ROC-AUC, Balanced Accuracy)\n",
            "\n",
            "Define verification functions to monitor accuracy levels.",
        ],
    },
    {
        "cell_type": "code",
        "execution_count": None,
        "metadata": {},
        "outputs": [],
        "source": [
            "def calculate_top_k_accuracy(logits, targets, k):\n",
            "    top_k_preds = np.argsort(logits, axis=1)[:, -k:]\n",
            "    correct = np.any(top_k_preds == targets[:, None], axis=1)\n",
            "    return np.mean(correct)\n",
            "\n",
            "def calculate_all_metrics(logits, labels):\n",
            "    preds = logits.argmax(axis=-1)\n",
            "    \n",
            "    acc1 = accuracy_score(labels, preds)\n",
            "    acc3 = calculate_top_k_accuracy(logits, labels, k=3)\n",
            "    acc5 = calculate_top_k_accuracy(logits, labels, k=5)\n",
            "    \n",
            "    balanced_acc = balanced_accuracy_score(labels, preds)\n",
            "    \n",
            "    prec, rec, f1_macro, _ = precision_recall_fscore_support(\n",
            "        labels, preds, average='macro', zero_division=0\n",
            "    )\n",
            "    _, _, f1_weighted, _ = precision_recall_fscore_support(\n",
            "        labels, preds, average='weighted', zero_division=0\n",
            "    )\n",
            "    \n",
            "    # ROC-AUC calculation (One-vs-Rest)\n",
            "    try:\n",
            "        probs = np.exp(logits) / np.sum(np.exp(logits), axis=-1, keepdims=True)\n",
            "        auc = roc_auc_score(labels, probs, multi_class='ovr', average='macro', labels=list(range(num_classes)))\n",
            "    except Exception:\n",
            "        auc = 1.0  # Fallback if splits miss rare labels\n",
            "        \n",
            "    return {\n",
            "        'top1_acc': acc1,\n",
            "        'top3_acc': acc3,\n",
            "        'top5_acc': acc5,\n",
            "        'balanced_acc': balanced_acc,\n",
            "        'precision': prec,\n",
            "        'recall': rec,\n",
            "        'macro_f1': f1_macro,\n",
            "        'weighted_f1': f1_weighted,\n",
            "        'roc_auc': auc\n",
            "    }",
        ],
    },
    {
        "cell_type": "markdown",
        "metadata": {},
        "source": ["## 6. Training & Validation Execution Loops"],
    },
    {
        "cell_type": "code",
        "execution_count": None,
        "metadata": {},
        "outputs": [],
        "source": [
            "def train_epoch(\n",
            "    model, loader, optimizer, scheduler, criterion, scaler, device, grad_accum=1, max_norm=1.0\n",
            "):\n",
            "    model.train()\n",
            "    total_loss = 0.0\n",
            "    optimizer.zero_grad()\n",
            "    \n",
            "    for idx, batch in enumerate(loader):\n",
            "        ids = batch['input_ids'].to(device)\n",
            "        mask = batch['attention_mask'].to(device)\n",
            "        lbls = batch['label'].to(device)\n",
            "        \n",
            "        with autocast():\n",
            "            outputs = model(ids, attention_mask=mask)\n",
            "            loss = criterion(outputs.logits, lbls)\n",
            "            loss_accum = loss / grad_accum\n",
            "            \n",
            "        scaler.scale(loss_accum).backward()\n",
            "        \n",
            "        if (idx + 1) % grad_accum == 0 or (idx + 1) == len(loader):\n",
            "            scaler.unscale_(optimizer)\n",
            "            nn.utils.clip_grad_norm_(model.parameters(), max_norm)\n",
            "            scaler.step(optimizer)\n",
            "            scaler.update()\n",
            "            optimizer.zero_grad()\n",
            "            scheduler.step()\n",
            "            \n",
            "        total_loss += loss.item() * ids.size(0)\n",
            "        \n",
            "    return total_loss / len(loader.dataset)\n",
            "\n",
            "def validate_epoch(model, loader, criterion, device):\n",
            "    model.eval()\n",
            "    total_loss = 0.0\n",
            "    all_logits = []\n",
            "    all_labels = []\n",
            "    \n",
            "    with torch.no_grad():\n",
            "        for batch in loader:\n",
            "            ids = batch['input_ids'].to(device)\n",
            "            mask = batch['attention_mask'].to(device)\n",
            "            lbls = batch['label'].to(device)\n",
            "            \n",
            "            outputs = model(ids, attention_mask=mask)\n",
            "            loss = criterion(outputs.logits, lbls)\n",
            "            \n",
            "            total_loss += loss.item() * ids.size(0)\n",
            "            all_logits.extend(outputs.logits.cpu().numpy())\n",
            "            all_labels.extend(lbls.cpu().numpy())\n",
            "            \n",
            "    metrics = calculate_all_metrics(np.array(all_logits), np.array(all_labels))\n",
            "    metrics['loss'] = total_loss / len(loader.dataset)\n",
            "    metrics['logits'] = np.array(all_logits)\n",
            "    metrics['labels'] = np.array(all_labels)\n",
            "    return metrics",
        ],
    },
    {
        "cell_type": "markdown",
        "metadata": {},
        "source": [
            "## 7. Hyperparameter Grid Search (with checkpoint recovery support)\n",
            "\n",
            "We check weight decay parameters alongside learning rate and batch size options. Epoch checkpoints are written at each epoch; if execution is interrupted, rerun this cell to resume training from the latest saved state.",
        ],
    },
    {
        "cell_type": "code",
        "execution_count": None,
        "metadata": {},
        "outputs": [],
        "source": [
            "MODEL_NAME = 'dmis-lab/biobert-base-cased-v1.1'\n",
            "tokenizer = AutoTokenizer.from_pretrained(MODEL_NAME)\n",
            "\n",
            "lrs = [5e-5, 3e-5, 2e-5]\n",
            "batch_sizes = [8, 16]\n",
            "weight_decays = [0.01, 0.05]\n",
            "max_epochs = 10\n",
            "patience = 3\n",
            "\n",
            "best_macro_f1 = -1.0\n",
            "best_cfg = None\n",
            "best_model_state = None\n",
            "best_history = None\n",
            "\n",
            "CHECKPOINT_PATH = './data/final/epoch_checkpoint.pt'\n",
            "\n",
            "# Check if previous run checkpoints exist to resume\n",
            "if os.path.exists(CHECKPOINT_PATH):\n",
            '    print("Found checkpoint. Resuming hyperparameter search pipeline...")\n',
            "    checkpoint = torch.load(CHECKPOINT_PATH)\n",
            "    start_run_idx = checkpoint['run_idx']\n",
            "    start_epoch = checkpoint['epoch'] + 1\n",
            "    best_macro_f1 = checkpoint['best_macro_f1']\n",
            "    best_cfg = checkpoint['best_cfg']\n",
            "    best_model_state = checkpoint['best_model_state']\n",
            "    best_history = checkpoint['best_history']\n",
            "    run_history = checkpoint['run_history']\n",
            "else:\n",
            "    start_run_idx = 0\n",
            "    start_epoch = 1\n",
            "    run_history = []\n",
            "\n",
            "# Compile grid of hyperparameters\n",
            "grid = []\n",
            "for bs in batch_sizes:\n",
            "    for lr in lrs:\n",
            "        for wd in weight_decays:\n",
            "            grid.append({'batch_size': bs, 'lr': lr, 'weight_decay': wd})\n",
            "\n",
            "for run_idx in range(start_run_idx, len(grid)):\n",
            "    cfg = grid[run_idx]\n",
            "    bs, lr, wd = cfg['batch_size'], cfg['lr'], cfg['weight_decay']\n",
            '    print(f"\\n--- Run {run_idx+1}/{len(grid)}: BS={bs} | LR={lr} | WD={wd} ---")\n',
            "    \n",
            "    train_dataset = ClinicalSymptomDataset(train_df, tokenizer)\n",
            "    val_dataset = ClinicalSymptomDataset(val_df, tokenizer)\n",
            "    \n",
            "    train_loader = DataLoader(train_dataset, batch_size=bs, shuffle=True)\n",
            "    val_loader = DataLoader(val_dataset, batch_size=bs, shuffle=False)\n",
            "    \n",
            "    set_seed(42)\n",
            "    config = AutoConfig.from_pretrained(MODEL_NAME, num_labels=num_classes)\n",
            "    config.classifier_dropout = 0.2\n",
            "    model = AutoModelForSequenceClassification.from_pretrained(MODEL_NAME, config=config).to(device)\n",
            "    \n",
            "    # Label Smoothing = 0.1\n",
            "    criterion = nn.CrossEntropyLoss(weight=weights_tensor, label_smoothing=0.1)\n",
            "    optimizer = optim.AdamW(model.parameters(), lr=lr, weight_decay=wd)\n",
            "    \n",
            "    steps = len(train_loader) * max_epochs\n",
            "    scheduler = get_cosine_schedule_with_warmup(optimizer, num_warmup_steps=int(steps*0.1), num_training_steps=steps)\n",
            "    scaler = GradScaler()\n",
            "    \n",
            "    patience_cnt = 0\n",
            "    best_val_f1_run = -1.0\n",
            "    run_model_state = None\n",
            "    \n",
            "    epoch_range = range(start_epoch if run_idx == start_run_idx else 1, max_epochs + 1)\n",
            "    \n",
            "    for epoch in epoch_range:\n",
            "        t_loss = train_epoch(model, train_loader, optimizer, scheduler, criterion, scaler, device)\n",
            "        val_res = validate_epoch(model, val_loader, criterion, device)\n",
            "        \n",
            "        run_history.append({\n",
            "            'epoch': epoch,\n",
            "            'train_loss': t_loss,\n",
            "            'val_loss': val_res['loss'],\n",
            "            'val_macro_f1': val_res['macro_f1'],\n",
            "            'val_acc': val_res['top1_acc'],\n",
            "            'lr': optimizer.param_groups[0]['lr']\n",
            "        })\n",
            "        \n",
            "        print(f\"  Epoch {epoch:02d} | Loss: {t_loss:.4f} (Val: {val_res['loss']:.4f}) | Val Macro F1: {val_res['macro_f1']:.4f}\")\n",
            "        \n",
            "        if val_res['macro_f1'] > best_val_f1_run:\n",
            "            best_val_f1_run = val_res['macro_f1']\n",
            "            patience_cnt = 0\n",
            "            run_model_state = {k: v.cpu().clone() for k, v in model.state_dict().items()}\n",
            "        else:\n",
            "            patience_cnt += 1\n",
            "            if patience_cnt >= patience:\n",
            '                print("  Early stopping triggered.")\n',
            "                break\n",
            "                \n",
            "        # Save intermediate epoch checkpoint\n",
            "        torch.save({\n",
            "            'run_idx': run_idx,\n",
            "            'epoch': epoch,\n",
            "            'best_macro_f1': best_macro_f1,\n",
            "            'best_cfg': best_cfg,\n",
            "            'best_model_state': best_model_state,\n",
            "            'best_history': best_history,\n",
            "            'run_history': run_history\n",
            "        }, CHECKPOINT_PATH)\n",
            "        \n",
            "    if best_val_f1_run > best_macro_f1:\n",
            "        best_macro_f1 = best_val_f1_run\n",
            "        best_cfg = {'batch_size': bs, 'lr': lr, 'weight_decay': wd, 'epoch': epoch}\n",
            "        best_model_state = run_model_state\n",
            "        best_history = list(run_history)\n",
            '        print(f"--> Best run updated! Val Macro F1: {best_macro_f1:.4f}")\n',
            "        \n",
            "    # Reset epoch counters for next config run\n",
            "    run_history = []\n",
            "    start_epoch = 1\n",
            "\n",
            "# Clean up checkpoint file\n",
            "if os.path.exists(CHECKPOINT_PATH):\n",
            "    os.remove(CHECKPOINT_PATH)\n",
            "\n",
            'print(f"\\nSearch Finished. Best: {best_cfg} | F1: {best_macro_f1:.4f}")',
        ],
    },
    {
        "cell_type": "markdown",
        "metadata": {},
        "source": ["## 8. Calibration scaling via Temperature parameter"],
    },
    {
        "cell_type": "code",
        "execution_count": None,
        "metadata": {},
        "outputs": [],
        "source": [
            "best_config = AutoConfig.from_pretrained(MODEL_NAME, num_labels=num_classes)\n",
            "best_config.classifier_dropout = 0.2\n",
            "best_model = AutoModelForSequenceClassification.from_pretrained(MODEL_NAME, config=best_config).to(device)\n",
            "best_model.load_state_dict({k: v.to(device) for k, v in best_model_state.items()})\n",
            "\n",
            "class TemperatureScaler(nn.Module):\n",
            "    def __init__(self):\n",
            "        super().__init__()\n",
            "        self.temperature = nn.Parameter(torch.ones(1))\n",
            "        \n",
            "    def forward(self, logits):\n",
            "        return logits / self.temperature\n",
            "        \n",
            "    def fit(self, val_loader, model, device):\n",
            "        model.eval()\n",
            "        logits_list, labels_list = [], []\n",
            "        with torch.no_grad():\n",
            "            for batch in val_loader:\n",
            "                ids = batch['input_ids'].to(device)\n",
            "                mask = batch['attention_mask'].to(device)\n",
            "                lbls = batch['label'].to(device)\n",
            "                outputs = model(ids, attention_mask=mask)\n",
            "                logits_list.append(outputs.logits)\n",
            "                labels_list.append(lbls)\n",
            "                \n",
            "        logits = torch.cat(logits_list).to(device)\n",
            "        labels = torch.cat(labels_list).to(device)\n",
            "        \n",
            "        nll_criterion = nn.CrossEntropyLoss()\n",
            "        optimizer = optim.LBFGS([self.temperature], lr=0.01, max_iter=50)\n",
            "        \n",
            "        def eval_val():\n",
            "            optimizer.zero_grad()\n",
            "            loss = nll_criterion(self.forward(logits), labels)\n",
            "            loss.backward()\n",
            "            return loss\n",
            "            \n",
            "        optimizer.step(eval_val)\n",
            "        return self.temperature.item()\n",
            "\n",
            "val_loader_cal = DataLoader(ClinicalSymptomDataset(val_df, tokenizer), batch_size=best_cfg['batch_size'], shuffle=False)\n",
            "scaler = TemperatureScaler().to(device)\n",
            "temp_scale = scaler.fit(val_loader_cal, best_model, device)\n",
            'print(f"Calibrated Temperature Value: {temp_scale:.4f}")',
        ],
    },
    {
        "cell_type": "markdown",
        "metadata": {},
        "source": ["## 9. Final Test Evaluation (Acc-1/3/5, ROC-AUC, Balanced Acc)"],
    },
    {
        "cell_type": "code",
        "execution_count": None,
        "metadata": {},
        "outputs": [],
        "source": [
            "test_dataset = ClinicalSymptomDataset(test_df, tokenizer)\n",
            "test_loader = DataLoader(test_dataset, batch_size=best_cfg['batch_size'], shuffle=False)\n",
            "\n",
            "criterion = nn.CrossEntropyLoss(weight=weights_tensor)\n",
            "test_res = validate_epoch(best_model, test_loader, criterion, device)\n",
            "\n",
            "# Apply calibration scaling\n",
            "calibrated_logits = test_res['logits'] / temp_scale\n",
            "probs = nn.functional.softmax(torch.tensor(calibrated_logits), dim=-1).numpy()\n",
            "predictions = probs.argmax(axis=-1)\n",
            "labels = test_res['labels']\n",
            "\n",
            "metrics = calculate_all_metrics(calibrated_logits, labels)\n",
            "\n",
            'print("===========================================")\n',
            'print("CALIBRATED TEST METRICS")\n',
            'print("===========================================")\n',
            "print(f\"Top-1 Accuracy: {metrics['top1_acc']:.4f}\")\n",
            "print(f\"Top-3 Accuracy: {metrics['top3_acc']:.4f}\")\n",
            "print(f\"Top-5 Accuracy: {metrics['top5_acc']:.4f}\")\n",
            "print(f\"Balanced Acc:   {metrics['balanced_acc']:.4f}\")\n",
            "print(f\"Macro F1:       {metrics['macro_f1']:.4f}\")\n",
            "print(f\"Weighted F1:    {metrics['weighted_f1']:.4f}\")\n",
            "print(f\"ROC-AUC:        {metrics['roc_auc']:.4f}\")\n",
            'print("===========================================")',
        ],
    },
    {
        "cell_type": "markdown",
        "metadata": {},
        "source": ["## 10. Visualizations (Learning curves, reliability, PR curves)"],
    },
    {
        "cell_type": "code",
        "execution_count": None,
        "metadata": {},
        "outputs": [],
        "source": [
            "VIS_DIR = './biobert_final_model/plots'\n",
            "os.makedirs(VIS_DIR, exist_ok=True)\n",
            "\n",
            "epochs = [h['epoch'] for h in best_history]\n",
            "t_losses = [h['train_loss'] for h in best_history]\n",
            "v_losses = [h['val_loss'] for h in best_history]\n",
            "\n",
            "# Loss Curve Plot\n",
            "plt.figure(figsize=(8, 5))\n",
            "plt.plot(epochs, t_losses, 'b-o', label='Train Loss')\n",
            "plt.plot(epochs, v_losses, 'r-s', label='Val Loss')\n",
            "plt.xlabel('Epochs')\n",
            "plt.ylabel('Loss')\n",
            "plt.title('Loss Curves')\n",
            "plt.legend()\n",
            "plt.grid(True)\n",
            "plt.savefig(os.path.join(VIS_DIR, 'learning_curve.png'), dpi=150)\n",
            "plt.close()\n",
            "\n",
            "# Confusion Matrix Plot\n",
            "cm = confusion_matrix(labels, predictions)\n",
            "plt.figure(figsize=(14, 12))\n",
            "sns.heatmap(\n",
            "    cm, annot=False, cmap='Blues', \n",
            "    xticklabels=[idx_to_disease[i] for i in sorted(list(set(labels)))],\n",
            "    yticklabels=[idx_to_disease[i] for i in sorted(list(set(labels)))]\n",
            ")\n",
            "plt.xlabel('Predicted')\n",
            "plt.ylabel('True')\n",
            "plt.tight_layout()\n",
            "plt.savefig(os.path.join(VIS_DIR, 'confusion_matrix.png'), dpi=150)\n",
            "plt.close()\n",
            "\n",
            "# Reliability Diagram / Calibration Curve\n",
            "confidences = probs.max(axis=-1)\n",
            "prob_true, prob_pred = calibration_curve(labels == predictions, confidences, n_bins=10)\n",
            "plt.figure(figsize=(7, 7))\n",
            "plt.plot(prob_pred, prob_true, 's-', label='Calibrated BioBERT')\n",
            "plt.plot([0, 1], [0, 1], 'k--', label='Perfect')\n",
            "plt.xlabel('Confidence')\n",
            "plt.ylabel('True Accuracy')\n",
            "plt.title('Reliability Diagram')\n",
            "plt.legend()\n",
            "plt.grid(True)\n",
            "plt.savefig(os.path.join(VIS_DIR, 'calibration_curve.png'), dpi=150)\n",
            "plt.close()\n",
            "\n",
            "# Precision-Recall curves\n",
            "y_bin = label_binarize(labels, classes=list(range(num_classes)))\n",
            "plt.figure(figsize=(8, 6))\n",
            "for i in sorted(list(set(labels))):\n",
            "    precision_class, recall_class, _ = precision_recall_curve(y_bin[:, i], probs[:, i])\n",
            "    plt.plot(recall_class, precision_class, lw=1.5, label=f'Class {idx_to_disease[i][:15]}...')\n",
            "plt.xlabel('Recall')\n",
            "plt.ylabel('Precision')\n",
            "plt.title('Precision-Recall Curve')\n",
            "plt.grid(True)\n",
            "plt.savefig(os.path.join(VIS_DIR, 'precision_recall_curve.png'), dpi=150)\n",
            "plt.close()\n",
            "\n",
            'print("Visualizations generated and exported successfully.")',
        ],
    },
    {
        "cell_type": "markdown",
        "metadata": {},
        "source": [
            "## 11. Clinical Explanation Database & Exporter\n",
            "\n",
            "To support patient explainability, we export a diagnostic clinical advice registry that maps diseases to specialists, tests, home care details, and emergency red flags.",
        ],
    },
    {
        "cell_type": "code",
        "execution_count": None,
        "metadata": {},
        "outputs": [],
        "source": [
            "EXPLANATIONS = {\n",
            '    "Fungal infection": {\n',
            '        "specialist": "Dermatologist",\n',
            '        "tests": ["Skin scraping microscopy", "Fungal culture", "Wood\'s lamp examination"],\n',
            '        "emergency_signs": "Spreading redness, severe swelling, throbbing pain, pus drainage, or fever.",\n',
            '        "home_care": "Keep the affected skin clean and dry. Avoid sharing towels or personal items.",\n',
            '        "lifestyle": "Wear loose, breathable cotton clothes. Shower immediately after sweating.",\n',
            '        "similar_diseases": ["Eczema", "Psoriasis", "Contact dermatitis"]\n',
            "    },\n",
            '    "GERD": {\n',
            '        "specialist": "Gastroenterologist",\n',
            '        "tests": ["Upper endoscopy", "Esophageal pH monitoring", "Barium swallow"],\n',
            '        "emergency_signs": "Difficulty swallowing, choking sensations, vomiting blood, or chest pain radiating to arm/jaw.",\n',
            '        "home_care": "Eat smaller meals. Avoid lying down for at least 2-3 hours after eating.",\n',
            '        "lifestyle": "Limit acidic, spicy, and fatty foods. Elevate the head of your bed during sleep.",\n',
            '        "similar_diseases": ["Gastritis", "Esophagitis", "Angina"]\n',
            "    },\n",
            '    "Chronic cholestasis": {\n',
            '        "specialist": "Hepatologist",\n',
            '        "tests": ["Liver function tests (LFTs)", "Abdominal ultrasound", "Serum bile acid assay"],\n',
            '        "emergency_signs": "Severe abdominal pain, confusion, extreme lethargy, or worsening dark urine and pale stools.",\n',
            '        "home_care": "Moisturize skin to ease itching. Stay well-hydrated.",\n',
            '        "lifestyle": "Avoid alcohol. Eat a balanced low-fat diet enriched with fat-soluble vitamins.",\n',
            '        "similar_diseases": ["Jaundice", "Hepatitis", "Gallstones"]\n',
            "    },\n",
            '    "Drug Reaction": {\n',
            '        "specialist": "Allergist / Dermatologist",\n',
            '        "tests": ["Allergy skin prick test", "Complete blood count (CBC)", "Skin biopsy"],\n',
            '        "emergency_signs": "Difficulty breathing, swelling of face/lips, blistered skin rash (Stevens-Johnson syndrome), or high fever.",\n',
            '        "home_care": "Immediately stop the suspected offending drug and consult your prescribing physician.",\n',
            '        "lifestyle": "Keep a written record of drug allergies and wear a medical alert identifier.",\n',
            '        "similar_diseases": ["Hives", "Viral exanthem", "Contact dermatitis"]\n',
            "    },\n",
            '    "Peptic ulcer diseae": {\n',
            '        "specialist": "Gastroenterologist",\n',
            '        "tests": ["H. pylori breath test", "Upper endoscopy", "Stool antigen test"],\n',
            '        "emergency_signs": "Sudden severe abdominal pain, vomiting blood or coffee-ground material, or black tarry stools.",\n',
            '        "home_care": "Avoid taking NSAIDs (like ibuprofen or aspirin). Eat small bland meals.",\n',
            '        "lifestyle": "Quit smoking and limit alcohol use. Manage psychological stress levels.",\n',
            '        "similar_diseases": ["Gastritis", "GERD", "Pancreatitis"]\n',
            "    },\n",
            '    "AIDS": {\n',
            '        "specialist": "Infectious Disease Specialist",\n',
            '        "tests": ["CD4 cell count", "HIV viral load test", "Opportunistic infection screening"],\n',
            '        "emergency_signs": "Severe shortness of breath, unexplained seizures, sudden high fever, or confusion.",\n',
            '        "home_care": "Strictly adhere to antiretroviral therapy (ART) schedule. Prevent infections by washing hands.",\n',
            '        "lifestyle": "Consume a nutrient-dense diet and maintain safe sex practices.",\n',
            '        "similar_diseases": ["Severe combined immunodeficiency", "Lymphoma"]\n',
            "    },\n",
            '    "Diabetes ": {\n',
            '        "specialist": "Endocrinologist",\n',
            '        "tests": ["HbA1c test", "Fasting blood glucose test", "Oral glucose tolerance test"],\n',
            '        "emergency_signs": "Fruity breath odor, rapid breathing, confusion, vomiting, or extremely high/low glucose levels.",\n',
            '        "home_care": "Monitor blood glucose regularly. Carry fast-acting glucose tablets for emergencies.",\n',
            '        "lifestyle": "Adopt a low-glycemic, fiber-rich diet. Engage in regular physical activity.",\n',
            '        "similar_diseases": ["Diabetes insipidus", "Prediabetes", "Metabolic syndrome"]\n',
            "    },\n",
            '    "Gastroenteritis": {\n',
            '        "specialist": "General Physician",\n',
            '        "tests": ["Stool culture", "Electrolyte panel", "Rotavirus stool test"],\n',
            '        "emergency_signs": "Inability to keep liquids down for 24 hours, extreme dizziness, blood in stool, or high fever.",\n',
            '        "home_care": "Sip Oral Rehydration Salts (ORS) frequently. Eat plain foods like bananas, rice, applesauce.",\n',
            '        "lifestyle": "Wash hands thoroughly with soap. Disinfect contaminated household surfaces.",\n',
            '        "similar_diseases": ["Food poisoning", "Irritable Bowel Syndrome (IBS)", "Inflammatory Bowel Disease"]\n',
            "    },\n",
            '    "Bronchial Asthma": {\n',
            '        "specialist": "Pulmonologist / Allergist",\n',
            '        "tests": ["Spirometry", "Peak expiratory flow rate", "Bronchoprovocation challenge"],\n',
            '        "emergency_signs": "Severe wheezing, blue lips/nails, chest tightness where rescue inhaler provides no relief.",\n',
            '        "home_care": "Keep your rescue inhaler accessible at all times. Sit upright during an attack.",\n',
            '        "lifestyle": "Identify and avoid triggers like pollen, dust mites, pet dander, and cold air.",\n',
            '        "similar_diseases": ["COPD", "Bronchitis", "Allergic rhinitis"]\n',
            "    },\n",
            '    "Hypertension ": {\n',
            '        "specialist": "Cardiologist",\n',
            '        "tests": ["Ambulatory blood pressure monitoring", "Electrocardiogram (ECG)", "Urinalysis"],\n',
            '        "emergency_signs": "Severe headache, chest pain, shortness of breath, blurry vision, or sudden weakness/numbness.",\n',
            '        "home_care": "Check blood pressure daily. Take prescribed medications exactly as directed.",\n',
            '        "lifestyle": "Limit sodium intake to under 1,500mg daily. Exercise regularly and limit alcohol.",\n',
            '        "similar_diseases": ["Chronic kidney disease", "Pheochromocytoma", "Hyperaldosteronism"]\n',
            "    },\n",
            '    "Migraine": {\n',
            '        "specialist": "Neurologist",\n',
            '        "tests": ["Brain MRI (to rule out other causes)", "Neurological evaluation"],\n',
            '        "emergency_signs": "Sudden \'thunderclap\' headache, fever, neck stiffness, confusion, or difficulty speaking.",\n',
            '        "home_care": "Rest in a dark, quiet room. Apply a cool compress to the forehead.",\n',
            '        "lifestyle": "Maintain a headache diary. Eat meals and sleep at consistent times every day.",\n',
            '        "similar_diseases": ["Tension headache", "Cluster headache", "Sinus headache"]\n',
            "    },\n",
            '    "Cervical spondylosis": {\n',
            '        "specialist": "Orthopedist / Physiotherapist",\n',
            '        "tests": ["Cervical spine X-ray", "Cervical MRI", "Electromyography (EMG)"],\n',
            '        "emergency_signs": "Loss of bladder or bowel control, severe numbness/weakness in arms or legs, or balance issues.",\n',
            '        "home_care": "Perform neck stretches regularly. Maintain an ergonomic workspace configuration.",\n',
            '        "lifestyle": "Avoid looking down at mobile phones for extended periods. Sleep with a supportive pillow.",\n',
            '        "similar_diseases": ["Herniated disc", "Spinal stenosis", "Fibromyalgia"]\n',
            "    },\n",
            '    "Paralysis (brain hemorrhage)": {\n',
            '        "specialist": "Neurologist / Neurosurgeon",\n',
            '        "tests": ["Non-contrast Head CT scan", "Brain MRI", "Coagulation profile"],\n',
            '        "emergency_signs": "FAST signs: Face dropping, Arm weakness, Speech difficulty -> Time to call emergency.",\n',
            '        "home_care": "Requires immediate emergency hospital admission. Do not give any food or liquids.",\n',
            '        "lifestyle": "Manage high blood pressure carefully. Stop smoking and limit alcohol intake.",\n',
            '        "similar_diseases": ["Ischemic stroke", "Transient Ischemic Attack (TIA)", "Brain tumor"]\n',
            "    },\n",
            '    "Jaundice": {\n',
            '        "specialist": "Hepatologist",\n',
            '        "tests": ["Serum bilirubin levels", "Viral hepatitis panel", "Abdominal ultrasound"],\n',
            '        "emergency_signs": "High fever with chills, severe right-sided abdominal pain, confusion, or dark blood in stool.",\n',
            '        "home_care": "Stay hydrated and avoid liver-taxing medications like paracetamol/acetaminophen.",\n',
            '        "lifestyle": "Eat a light low-fat diet. Completely avoid alcohol consumption.",\n',
            '        "similar_diseases": ["Hepatitis", "Cirrhosis", "Hemolytic anemia"]\n',
            "    },\n",
            '    "Malaria": {\n',
            '        "specialist": "Infectious Disease Specialist",\n',
            '        "tests": ["Thick and thin blood smears", "Rapid diagnostic test (RDT)", "Complete blood count (CBC)"],\n',
            '        "emergency_signs": "Confusion, seizures, breathing difficulties, extreme fatigue, or yellowing of the eyes.",\n',
            '        "home_care": "Take prescribed antimalarial medications exactly as instructed by a physician.",\n',
            '        "lifestyle": "Use mosquito nets, insect repellents, and wear long sleeves during evening hours.",\n',
            '        "similar_diseases": ["Dengue fever", "Typhoid fever", "Leptospirosis"]\n',
            "    },\n",
            '    "Chicken pox": {\n',
            '        "specialist": "Pediatrician / General Physician",\n',
            '        "tests": ["Clinical diagnosis", "PCR skin lesion swab", "Varicella-zoster IgM antibody test"],\n',
            '        "emergency_signs": "Rash spreading to eyes, severe cough, extreme drowsiness, or secondary bacterial infection.",\n',
            '        "home_care": "Use calamine lotion to soothe itching. Rest and avoid scratching blisters.",\n',
            '        "lifestyle": "Quarantine to avoid spreading the virus. Get vaccinated if eligible.",\n',
            '        "similar_diseases": ["Measles", "Hand-foot-and-mouth disease", "Hives"]\n',
            "    },\n",
            '    "Dengue": {\n',
            '        "specialist": "Infectious Disease Specialist",\n',
            '        "tests": ["Dengue NS1 antigen test", "Platelet count monitoring", "Dengue IgM/IgG ELISA"],\n',
            '        "emergency_signs": "Severe abdominal pain, persistent vomiting, bleeding gums, blood in vomit, or rapid drop in platelets.",\n',
            '        "home_care": "Stay hydrated. Take paracetamol for fever; DO NOT take ibuprofen or aspirin.",\n',
            '        "lifestyle": "Eliminate standing water around the home to prevent mosquito breeding.",\n',
            '        "similar_diseases": ["Malaria", "Zika virus", "Chikungunya"]\n',
            "    },\n",
            '    "Typhoid": {\n',
            '        "specialist": "Infectious Disease Specialist",\n',
            '        "tests": ["Blood culture", "Widal test (low specificity)", "Stool culture"],\n',
            '        "emergency_signs": "Severe abdominal pain with swelling, blood in stool, persistent high fever, or confusion.",\n',
            '        "home_care": "Complete the entire course of prescribed antibiotics. Hydrate using clean, boiled water.",\n',
            '        "lifestyle": "Avoid raw foods, street foods, and drinks containing unpurified ice.",\n',
            '        "similar_diseases": ["Malaria", "Gastroenteritis", "Typhus"]\n',
            "    },\n",
            '    "hepatitis A": {\n',
            '        "specialist": "Hepatologist",\n',
            '        "tests": ["Hepatitis A IgM antibody test", "Liver function test (LFT)"],\n',
            '        "emergency_signs": "Persistent vomiting, extreme sleepiness, yellowing of skin/eyes, or bleeding issues.",\n',
            '        "home_care": "Rest and avoid alcohol. Eat small, frequent meals if nauseous.",\n',
            '        "lifestyle": "Practice strict hand hygiene. Get the Hepatitis A vaccine.",\n',
            '        "similar_diseases": ["Hepatitis B", "Jaundice", "Epstein-Barr Virus"]\n',
            "    },\n",
            '    "Hepatitis B": {\n',
            '        "specialist": "Hepatologist",\n',
            '        "tests": ["HBsAg screening test", "HBV DNA viral load", "Liver ultrasound"],\n',
            '        "emergency_signs": "Severe abdominal pain, swelling of legs/abdomen, confusion, or dark vomit.",\n',
            '        "home_care": "Avoid self-prescribed medications. Keep regular appointments for monitoring.",\n',
            '        "lifestyle": "Do not share personal grooming items like razors or toothbrushes.",\n',
            '        "similar_diseases": ["Hepatitis C", "Hepatitis A", "Cirrhosis"]\n',
            "    },\n",
            '    "Hepatitis C": {\n',
            '        "specialist": "Hepatologist",\n',
            '        "tests": ["HCV antibody screening", "HCV RNA PCR test", "FibroScan"],\n',
            '        "emergency_signs": "Confusion, sudden high fever, vomiting blood, or swelling in the legs/ankles.",\n',
            '        "home_care": "Follow your direct-acting antiviral medication plan. Minimize liver strain.",\n',
            '        "lifestyle": "Never share needles or syringes. Get checked for comorbidities.",\n',
            '        "similar_diseases": ["Hepatitis B", "Alcoholic liver disease"]\n',
            "    },\n",
            '    "Hepatitis D": {\n',
            '        "specialist": "Hepatologist",\n',
            '        "tests": ["Anti-HDV antibody test", "HDV RNA PCR", "Hepatitis B status check"],\n',
            '        "emergency_signs": "Rapidly worsening jaundice, confusion, severe lethargy, or bruising/bleeding.",\n',
            '        "home_care": "Manage Hepatitis B infection since HDV requires HBV to replicate.",\n',
            '        "lifestyle": "Avoid any high-risk exposures. Consult a transplant center if severe.",\n',
            '        "similar_diseases": ["Hepatitis B coinfection", "Fulminant hepatic failure"]\n',
            "    },\n",
            '    "Hepatitis E": {\n',
            '        "specialist": "Hepatologist",\n',
            '        "tests": ["Hepatitis E IgM test", "HEV RNA in stool/blood"],\n',
            '        "emergency_signs": "Persistent vomiting, extreme drowsiness, yellow eyes, especially critical if pregnant.",\n',
            '        "home_care": "Stay hydrated and rest. Avoid pregnancy complications via close monitoring.",\n',
            '        "lifestyle": "Drink only safe, boiled or bottled water. Avoid undercooked pork/wild game.",\n',
            '        "similar_diseases": ["Hepatitis A", "Jaundice"]\n',
            "    },\n",
            '    "Alcoholic hepatitis": {\n',
            '        "specialist": "Hepatologist / Gastroenterologist",\n',
            '        "tests": ["Liver biopsy", "Complete blood count (CBC)", "Abdominal CT scan"],\n',
            '        "emergency_signs": "Severe abdominal swelling, confusion, vomiting blood, or sudden high fever.",\n',
            '        "home_care": "Complete and absolute cessation of alcohol consumption is mandatory.",\n',
            '        "lifestyle": "Eat a high-protein, calorie-rich diet under medical guidance.",\n',
            '        "similar_diseases": ["NASH", "Cirrhosis", "Viral hepatitis"]\n',
            "    },\n",
            '    "Tuberculosis": {\n',
            '        "specialist": "Pulmonologist / Infectious Disease Specialist",\n',
            '        "tests": ["Sputum smear microscopy", "GeneXpert MTB/RIF test", "Chest X-ray"],\n',
            '        "emergency_signs": "Coughing up large amounts of blood, severe chest pain, or sudden shortness of breath.",\n',
            '        "home_care": "Strict adherence to the 6-month anti-TB drug schedule is essential to prevent resistance.",\n',
            '        "lifestyle": "Wear a mask to protect others. Ensure good ventilation in living areas.",\n',
            '        "similar_diseases": ["Pneumonia", "Lung cancer", "Sarcoidosis"]\n',
            "    },\n",
            '    "Common Cold": {\n',
            '        "specialist": "General Physician",\n',
            '        "tests": ["Clinical diagnosis", "Rapid influenza test (to rule out flu)"],\n',
            '        "emergency_signs": "Difficulty breathing, wheezing, high persistent fever, or severe ear pain.",\n',
            '        "home_care": "Stay hydrated, rest, and use saline nasal drops. Take warm liquids.",\n',
            '        "lifestyle": "Wash hands frequently. Cover your mouth when coughing or sneezing.",\n',
            '        "similar_diseases": ["Influenza", "Allergic rhinitis", "Sinusitis"]\n',
            "    },\n",
            '    "Pneumonia": {\n',
            '        "specialist": "Pulmonologist",\n',
            '        "tests": ["Chest X-ray", "Sputum culture", "Pulse oximetry"],\n',
            '        "emergency_signs": "Difficulty breathing, chest pain when breathing, confusion (especially in elderly), or blue lips.",\n',
            '        "home_care": "Complete all prescribed antibiotics. Rest and use a humidifier.",\n',
            '        "lifestyle": "Avoid tobacco smoke. Get the pneumococcal vaccine.",\n',
            '        "similar_diseases": ["Bronchitis", "Tuberculosis", "Asthma flare-up"]\n',
            "    },\n",
            '    "Dimorphic hemmorhoids(piles)": {\n',
            '        "specialist": "Proctologist / Colorectal Surgeon",\n',
            '        "tests": ["Anoscopy", "Sigmoidoscopy", "Digital rectal examination"],\n',
            '        "emergency_signs": "Severe persistent rectal bleeding, extreme pain, or dizziness/faintness from blood loss.",\n',
            '        "home_care": "Take warm sitz baths. Avoid straining during bowel movements.",\n',
            '        "lifestyle": "Eat a high-fiber diet, drink plenty of water, and stay active.",\n',
            '        "similar_diseases": ["Anal fissure", "Colorectal cancer", "Inflammatory Bowel Disease"]\n',
            "    },\n",
            '    "Heart attack": {\n',
            '        "specialist": "Cardiologist",\n',
            '        "tests": ["12-lead Electrocardiogram (ECG)", "Troponin blood test", "Coronary angiogram"],\n',
            '        "emergency_signs": "Crushing chest pain radiating to arm, neck, or jaw; shortness of breath; sweating; cold clammy skin.",\n',
            '        "home_care": "This is a life-threatening emergency. Call ambulance immediately. Chew an aspirin if advised by dispatch.",\n',
            '        "lifestyle": "Follow a heart-healthy diet. Avoid smoking and exercise regularly after recovery.",\n',
            '        "similar_diseases": ["Angina", "GERD / Heartburn", "Panic attack"]\n',
            "    },\n",
            '    "Varicose veins": {\n',
            '        "specialist": "Vascular Surgeon",\n',
            '        "tests": ["Duplex ultrasound of leg veins", "Visual examination"],\n',
            '        "emergency_signs": "Sudden swelling of one leg, redness, warmth, or chest pain/shortness of breath (signs of DVT/PE).",\n',
            '        "home_care": "Wear compression stockings. Elevate legs above heart level when resting.",\n',
            '        "lifestyle": "Avoid standing or sitting for long periods. Exercise to improve calf muscle tone.",\n',
            '        "similar_diseases": ["Deep Vein Thrombosis (DVT)", "Thrombophlebitis", "Lymphedema"]\n',
            "    },\n",
            '    "Hypothyroidism": {\n',
            '        "specialist": "Endocrinologist",\n',
            '        "tests": ["TSH (Thyroid Stimulating Hormone) test", "Free T4 level"],\n',
            '        "emergency_signs": "Extreme fatigue, confusion, low body temperature, or swelling of the face/tongue.",\n',
            '        "home_care": "Take levothyroxine daily on an empty stomach as prescribed by your doctor.",\n',
            '        "lifestyle": "Eat a fiber-rich diet to combat constipation. Exercise regularly.",\n',
            '        "similar_diseases": ["Depression", "Chronic Fatigue Syndrome", "Anemia"]\n',
            "    },\n",
            '    "Hyperthyroidism": {\n',
            '        "specialist": "Endocrinologist",\n',
            '        "tests": ["TSH, Free T3, and Free T4 tests", "Thyroid scan and radioactive iodine uptake"],\n',
            '        "emergency_signs": "Rapid heart rate (arrhythmia), fever, confusion, vomiting, or extreme agitation (Thyroid Storm).",\n',
            '        "home_care": "Monitor heart rate. Take beta-blockers or antithyroid medicines as prescribed.",\n',
            '        "lifestyle": "Manage stress, eat calorie-dense foods if losing weight rapidly, and avoid excess iodine.",\n',
            '        "similar_diseases": ["Anxiety disorder", "Graves\' disease", "Pheochromocytoma"]\n',
            "    },\n",
            '    "Hypoglycemia": {\n',
            '        "specialist": "Endocrinologist",\n',
            '        "tests": ["Blood glucose level monitoring", "Fast-acting glucose challenge"],\n',
            '        "emergency_signs": "Confusion, loss of consciousness, seizures, or inability to swallow safely.",\n',
            '        "home_care": "Apply the 15-15 rule: consume 15g fast sugar, wait 15 minutes, check blood glucose.",\n',
            '        "lifestyle": "Eat regular, balanced meals. Always carry fast-acting carbohydrates with you.",\n',
            '        "similar_diseases": ["Panic attack", "Stroke", "Vasovagal syncope"]\n',
            "    },\n",
            '    "Osteoarthristis": {\n',
            '        "specialist": "Rheumatologist / Orthopedist",\n',
            '        "tests": ["Joint X-ray", "Joint fluid analysis (to rule out infection)"],\n',
            '        "emergency_signs": "Inability to bear weight on the joint, sudden severe swelling, warmth, or redness.",\n',
            '        "home_care": "Apply ice packs for swelling and warm packs for stiffness. Use joint supports.",\n',
            '        "lifestyle": "Maintain a healthy weight to reduce joint load. Do low-impact exercises like swimming.",\n',
            '        "similar_diseases": ["Rheumatoid arthritis", "Gout", "Bursitis"]\n',
            "    },\n",
            '    "Arthritis": {\n',
            '        "specialist": "Rheumatologist",\n',
            '        "tests": ["Rheumatoid Factor (RF) test", "Anti-CCP antibodies", "Erythrocyte sedimentation rate (ESR)"],\n',
            '        "emergency_signs": "High fever accompanied by joint swelling (Septic arthritis), or severe joint pain with chills.",\n',
            '        "home_care": "Balance rest with gentle range-of-motion exercises. Use assistive devices.",\n',
            '        "lifestyle": "Adopt an anti-inflammatory diet (rich in omega-3). Avoid joint strain.",\n',
            '        "similar_diseases": ["Osteoarthritis", "Lupus", "Psoriatic arthritis"]\n',
            "    },\n",
            '    "(vertigo) Paroymsal  Positional Vertigo": {\n',
            '        "specialist": "ENT Specialist (Otolaryngologist)",\n',
            '        "tests": ["Dix-Hallpike maneuver", "Videonystagmography (VNG)"],\n',
            '        "emergency_signs": "Vertigo with double vision, slurred speech, limb weakness, difficulty walking, or chest pain.",\n',
            '        "home_care": "Sit down immediately during a vertigo episode. Perform the Epley maneuver under guidance.",\n',
            '        "lifestyle": "Avoid sudden neck movements and sleeping flat on your back.",\n',
            '        "similar_diseases": ["Meniere\'s disease", "Labyrinthitis", "Vestibular migraine"]\n',
            "    },\n",
            '    "Acne": {\n',
            '        "specialist": "Dermatologist",\n',
            '        "tests": ["Clinical inspection", "Hormonal panel (if endocrine cause suspected)"],\n',
            '        "emergency_signs": "Extremely painful, deep nodules or cysts with signs of spreading infection/fever.",\n',
            '        "home_care": "Wash skin gently twice daily. Avoid squeezing or popping pimples.",\n',
            '        "lifestyle": "Use non-comedogenic cosmetics. Wash hair regularly to reduce oils.",\n',
            '        "similar_diseases": ["Rosacea", "Folliculitis", "Perioral dermatitis"]\n',
            "    },\n",
            '    "Urinary tract infection": {\n',
            '        "specialist": "Urologist / General Physician",\n',
            '        "tests": ["Urinalysis", "Urine culture and sensitivity"],\n',
            '        "emergency_signs": "High fever, flank/lower back pain, chills, nausea, vomiting (signs of kidney infection).",\n',
            '        "home_care": "Drink plenty of water to flush out bacteria. Avoid carbonated/caffeinated drinks.",\n',
            '        "lifestyle": "Practice good hygiene. Wipe front to back and urinate after intercourse.",\n',
            '        "similar_diseases": ["Interstitual cystitis", "Vaginitis", "Urethritis"]\n',
            "    },\n",
            '    "Psoriasis": {\n',
            '        "specialist": "Dermatologist",\n',
            '        "tests": ["Skin biopsy", "Clinical inspection"],\n',
            '        "emergency_signs": "Pustules all over the body, red skin peeling, chills, fever (Erythrodermic psoriasis emergency).",\n',
            '        "home_care": "Apply prescribed emollients regularly. Take warm baths using colloidal oatmeal.",\n',
            '        "lifestyle": "Identify and avoid triggers like stress, skin injuries, and smoking.",\n',
            '        "similar_diseases": ["Eczema", "Seborrheic dermatitis", "Lichen planus"]\n',
            "    },\n",
            '    "Impetigo": {\n',
            '        "specialist": "Dermatologist / Pediatrician",\n',
            '        "tests": ["Wound swab culture", "Clinical inspection"],\n',
            '        "emergency_signs": "Rash spreading rapidly, red streaks extending from the sores, or high fever.",\n',
            '        "home_care": "Keep sores covered with clean gauze. Wash hands thoroughly with soap.",\n',
            '        "lifestyle": "Avoid sharing clothes or linens with infected individuals to prevent transmission.",\n',
            '        "similar_diseases": ["Ecthyma", "Herpes simplex", "Scabies"]\n',
            "    }\n",
            "}\n",
            "\n",
            "# Write explanations database to exported model directory\n",
            "os.makedirs('./biobert_final_model', exist_ok=True)\n",
            "with open('./biobert_final_model/clinical_explanations.json', 'w', encoding='utf-8') as f:\n",
            "    json.dump(EXPLANATIONS, f, indent=4)\n",
            'print("Clinical explanations database written successfully.")',
        ],
    },
    {
        "cell_type": "markdown",
        "metadata": {},
        "source": ["## 12. Save Models, Tokenizer, Scaler, and Configuration details"],
    },
    {
        "cell_type": "code",
        "execution_count": None,
        "metadata": {},
        "outputs": [],
        "source": [
            "EXPORT_DIR = './biobert_final_model'\n",
            "\n",
            "# 1. Save weights\n",
            "best_model.save_pretrained(EXPORT_DIR)\n",
            "\n",
            "# 2. Save tokenizer\n",
            "tokenizer.save_pretrained(EXPORT_DIR)\n",
            "\n",
            "# 3. Save Label Encoder\n",
            "with open(os.path.join(EXPORT_DIR, 'label_encoder.pkl'), 'wb') as f:\n",
            "    pickle.dump(label_encoder, f)\n",
            "\n",
            "# 4. Save Temperature Scaler Parameter\n",
            "with open(os.path.join(EXPORT_DIR, 'temperature_scaler.json'), 'w') as f:\n",
            "    json.dump({'temperature': temp_scale}, f, indent=4)\n",
            "\n",
            "# 5. Save class weights JSON\n",
            "with open(os.path.join(EXPORT_DIR, 'class_weights.json'), 'w') as f:\n",
            "    json.dump(class_weights_dict, f, indent=4)\n",
            "\n",
            "# 6. Save best configuration details\n",
            "with open(os.path.join(EXPORT_DIR, 'training_config.json'), 'w') as f:\n",
            "    json.dump({\n",
            "        'base_model': MODEL_NAME,\n",
            "        'max_length': 128,\n",
            "        'best_hyperparameters': best_cfg,\n",
            "        'num_classes': num_classes\n",
            "    }, f, indent=4)\n",
            "\n",
            "# 7. Save metrics JSON\n",
            "metrics_json = {\n",
            "    'accuracy': float(metrics['top1_acc']),\n",
            "    'top3_accuracy': float(metrics['top3_acc']),\n",
            "    'top5_accuracy': float(metrics['top5_acc']),\n",
            "    'balanced_accuracy': float(metrics['balanced_acc']),\n",
            "    'precision_macro': float(metrics['precision']),\n",
            "    'recall_macro': float(metrics['recall']),\n",
            "    'f1_macro': float(metrics['macro_f1']),\n",
            "    'f1_weighted': float(metrics['weighted_f1']),\n",
            "    'roc_auc_macro': float(metrics['roc_auc']),\n",
            "    'temperature': float(temp_scale)\n",
            "}\n",
            "with open(os.path.join(EXPORT_DIR, 'metrics.json'), 'w') as f:\n",
            "    json.dump(metrics_json, f, indent=4)\n",
            "\n",
            "total_params = sum(p.numel() for p in best_model.parameters())\n",
            "trainable_params = sum(p.numel() for p in best_model.parameters() if p.requires_grad)\n",
            "model_size_mb = (total_params * 4) / (1024 * 1024)\n",
            "\n",
            'print(f"All output weights exported to: {EXPORT_DIR}")',
        ],
    },
    {"cell_type": "markdown", "metadata": {}, "source": ["### Generate markdown training report"]},
    {
        "cell_type": "code",
        "execution_count": None,
        "metadata": {},
        "outputs": [],
        "source": [
            "report_path = os.path.join(EXPORT_DIR, 'training_report.md')\n",
            "\n",
            'report_md = f"""# Upgraded BioBERT Fine-Tuning Execution Report\n',
            "\n",
            "## 1. System Metadata\n",
            "- **Training Date**: {datetime.now().strftime('%Y-%m-%d %H:%M:%S')}\n",
            "- **GPU Type**: {gpu_name}\n",
            "- **Base Model**: `{MODEL_NAME}`\n",
            "- **Max Seq Length**: 128\n",
            "\n",
            "## 2. Dataset Split Summary\n",
            "- **Training Samples**: {len(train_df)}\n",
            "- **Validation Samples**: {len(val_df)}\n",
            "- **Testing Samples**: {len(test_df)}\n",
            "- **Number of Disease Classes**: {num_classes}\n",
            "\n",
            "## 3. Best Training Configuration\n",
            "- **Best Batch Size**: {best_cfg['batch_size']}\n",
            "- **Best Learning Rate**: {best_cfg['lr']}\n",
            "- **Best Weight Decay**: {best_cfg['weight_decay']}\n",
            "- **Best Epoch**: {best_cfg['epoch']}\n",
            "- **Calibration Temperature Scale**: {temp_scale:.4f}\n",
            "\n",
            "## 4. Model Size Details\n",
            "- **Total Parameters**: {total_params:,}\n",
            "- **Trainable Parameters**: {trainable_params:,}\n",
            "- **Estimated Size on Disk**: {model_size_mb:.2f} MB\n",
            "\n",
            "## 5. Final Calibrated Test Metrics\n",
            "- **Top-1 Accuracy**: {metrics['top1_acc']:.4f}\n",
            "- **Top-3 Accuracy**: {metrics['top3_acc']:.4f}\n",
            "- **Top-5 Accuracy**: {metrics['top5_acc']:.4f}\n",
            "- **Balanced Accuracy**: {metrics['balanced_acc']:.4f}\n",
            "- **Test Precision (Macro)**: {metrics['precision']:.4f}\n",
            "- **Test Recall (Macro)**: {metrics['recall']:.4f}\n",
            "- **Test F1 (Macro)**: {metrics['macro_f1']:.4f}\n",
            "- **Test F1 (Weighted)**: {metrics['weighted_f1']:.4f}\n",
            "- **ROC-AUC (OVR Macro)**: {metrics['roc_auc']:.4f}\n",
            '"""\n',
            "\n",
            "with open(report_path, 'w', encoding='utf-8') as f:\n",
            "    f.write(report_md)\n",
            "\n",
            'print(f"Saved final execution report to: {report_path}")',
        ],
    },
    {"cell_type": "markdown", "metadata": {}, "source": ["### Export Back to Google Drive"]},
    {
        "cell_type": "code",
        "execution_count": None,
        "metadata": {},
        "outputs": [],
        "source": [
            "drive_export_dest = '/content/drive/MyDrive/AI-Medical-Diagnosis-Assistant/models/biobert_final_model'\n",
            "\n",
            "if os.path.exists(drive_export_dest):\n",
            "    shutil.rmtree(drive_export_dest)\n",
            "\n",
            "shutil.copytree(EXPORT_DIR, drive_export_dest)\n",
            'print(f"========================================================================================")\n',
            'print(f"Pipeline complete. All artifacts copied to Drive location:")\n',
            'print(f"  {drive_export_dest}")\n',
            'print(f"========================================================================================")',
        ],
    },
]

# Build ipynb structure
notebook_json = {
    "cells": cells,
    "metadata": {
        "colab": {"provenance": []},
        "kernelspec": {"display_name": "Python 3", "language": "python", "name": "python3"},
        "language_info": {"name": "python"},
    },
    "nbformat": 4,
    "nbformat_minor": 0,
}

# ─────────────────────────────────────────────────────────────────────────────
# Write Notebook
# ─────────────────────────────────────────────────────────────────────────────

NOTEBOOK_PATH.parent.mkdir(parents=True, exist_ok=True)
with open(NOTEBOOK_PATH, "w", encoding="utf-8") as f:
    json.dump(notebook_json, f, indent=2)

print(f"[notebook] Generated Upgraded Google Colab notebook at: {NOTEBOOK_PATH}")
